### ISSUE TITLE
Structure placement issue on Snowdust terrain

### ISSUE THREAD

**Issue by mbreiteneder** [Vailorium/askrs-archives-web#5]
Snowdust terrain allows the placement of structures on the forest tile in column 3.

![Screenshot_20210128_143041](https://user-images.githubusercontent.com/17741087/106145324-aeffce00-6175-11eb-83be-076676382094.png)

**Comment by Vailorium** [comment]
Aah I can't believe I didn't pick that up - thanks for reporting, the issue has now been fixed (might require you to empty cache to update).
